language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

install: composer install

before_script:
  - composer require satooshi/php-coveralls

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then travis_retry php vendor/bin/php-coveralls -v; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then travis_retry php vendor/bin/php-coveralls -v; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.2' ]]; then travis_retry php vendor/bin/php-coveralls -v; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.3' ]]; then travis_retry php vendor/bin/php-coveralls -v; fi